---
title: "plot.ly and dashboards"
author: "Zihan Xiong"
date: "2025-10-21"
output: html_document
---
# web-centric tools
plotly provides a platform for online data analytics and visualizations;
build on of HTML etc.;
"grammar of graphics" in ggplot;
convey a lot of info in a easy-to-understand format.

```{r, message=FALSE}
library(tidyverse)
library(plotly)

library(p8105.datasets)
```

Lets load the Airbnb datsets.

```{r}
data("nyc_airbnb")

nyc_airbnb=nyc_airbnb|>
  mutate(
    rating=review_scores_location/2
  )|>
  select(
    neighbourhood_group, neighbourhood, rating, price, room_type, lat, long
  )|>
  filter(
    neighbourhood_group=="Manhattan",
    room_type=="Entire home/apt",
    price <= 500,
    price >=100
  )

nyc_airbnb
```

Let's make a scatterplot but interactive at this time.

```{r}
nyc_airbnb |>
  mutate(
    label=str_c("Price:&", price, "\nRating: ", rating)
  )|>
  plot_ly(
    x = ~lat, y=~long, color=~price, 
    text=~label,
    type = "scatter", mode = "markers", alpha=.5
  )
```

